### ISSUE TITLE
Exclusion of algorithms is not configurable

### ISSUE THREAD

**Issue by joshavant** [wo80/essentia#3]
While investigating #2, I discovered that this line:

https://github.com/wo80/essentia/blob/65f6e69344be1b0c4f1334cd759b5b0b0775ea7c/CMakeLists.txt#L157

Always excludes all of the implementations in `src/algorithms` from the build product, with no exposed build configuration option to include them.

For my own purposes, accessing those algorithms is a big motivation for why I'm trying to get Essentia working.

Are there technical reasons for doing this (e.g. additional dependency/linking requirements, etc)?

If not, it would seem valuable to add a build configuration option to enable algorithms in the build output.

(Also, if such a build configuration option does get added, could I also ask that the de-facto project documentation, [located here](http://wo80.bplaced.net/posts/2024/01-compile-essentia-cmake/), also be updated?)

**Comment by wo80** [comment]
> Are there technical reasons for doing this (e.g. additional dependency/linking requirements, etc)?

No technical reason, but it's what the waf install does:
https://github.com/wo80/essentia/blob/a770d1bc2b3f9fb3cefa835dcf5eb6a6e05e0f07/src/wscript#L559

Only the headers of the `essentia` subfolder are added. This is because the algorithms are usually created through the factory, so the actual algorithm header isn't needed. See for example
https://github.com/wo80/essentia/blob/a770d1bc2b3f9fb3cefa835dcf5eb6a6e05e0f07/src/examples/onset_detector.cpp#L85-L89

> If not, it would seem valuable to add a build configuration option to enable algorithms in the build output.

By default, I think the CMake install should behave like the original waf install. But if you need those headers, I'd be open to adding an option to enable this.

**Comment by joshavant** [comment]
Ah! I'm new to the library wasn't aware that's how that works. It seems reasonable, overall, match the behavior of the waf file that this is replacing, so I'll close this. 👍
